export const en={
    titre:"Step Into My World",
    home:"Home",
    skills:"Skills",
    experiences:"Experiences",
    certificates:"Certificates",
    language:"Language",
    // ====================home=============================
    b:"Hello there ",
    b1:" I am ",
    b2:"I am a passionate",
    b3:"full-stack developer.",
    pre1:"Dedicated to creating smart, efficient, and user-friendly digital solutions.",
    pre2:"Whether it’s web, mobile, or backend development, I love turning ideas into functional applications. Welcome to my portfolio.",
    pre3:"Feel free to explore my projects, skills, and experience!",
    cv:"Download cv",
    Edu:"Education",
    In:"Present",
    Final:"Final year of the State Engineer program.",
    Fac:"Faculty of Science and Technology of Fez.",
    Major1:"Specialization in Intelligent, Communicating, and Mobile Systems (SICOM)",
    Bach:"Bachelor’s Degree in Science and Technology",
    fac1:"Faculty of Science and Technology, Mohammedia.",
    Spe:"Specialization in Computer Science, Networks, and Multimedia.",
    bach1:"University Diploma in Science and Technology.",
    spe:"Specialization in Mathematics, Computer Science, and Physics.",
    Bac:"Baccalaureate in Physical and Chemical Sciences – Casablanca.",
    ve1:"French version",
    ve2:"English version",
    // ======================skills========================
    s1: "Programming languages",
s2: "Libraries and frameworks",
s3: "Development environments (IDEs)",
s4: "Project design and planning",
s5: "Office tools",
s6: "Databases",
s7: "Embedded systems",
    // =======================experience==================
    a: "Show details",
m: "Hide details",
te1: "Internships",
en: "Technical environment:",
e1: "Design and development of a web application for the digitization of the FST library services.",
ed1: "The purpose of this project is to design and develop a web application dedicated to the digital management of the scientific books in our faculty’s library. This platform also provides a collaborative space for students and teachers, allowing them to exchange documents such as lectures, tutorials, and lab reports. In addition, a discussion forum has been integrated to promote better communication and knowledge sharing within the academic community.",
e2: "Design and development of a mobile application allowing grocery store owners to place their orders online.",
ed2: "This project involves designing and developing a mobile application for grocery store owners, allowing them to place their orders online with their main supplier, Centrale Danone. The application offers several key features, such as real-time order tracking, client (grocery store) management through a personalized dashboard, and a reporting module for sales and performance analysis. The main goal of this solution is to digitalize the ordering process between Centrale Danone and its retailers, facilitate communication and logistics, and improve business management and tracking through a modern, intuitive, and accessible interface.",
e3: "Design and development of a mobile application for managing a dental clinic.",
ed3: "This project focuses on the design and development of a mobile application dedicated to the complete management of a dental clinic. The goal is to provide an integrated digital solution that centralizes and simplifies the clinic’s main operations, including appointment management with an interactive calendar, patient medical record management (history, diagnoses, and treatments), and medication and prescription management. The application also includes a support and communication service for patients, allowing them to ask questions, receive automatic appointment reminders, and track their treatments. This solution aims to improve internal organization, optimize medical follow-up, and strengthen the relationship between the practitioner and patients through a modern, ergonomic, and secure interface.",
te2: "Academic Projects",
e4: "Development of an intelligent system for road sign detection.",
ed4: "This project focuses on designing and implementing an intelligent real-time road sign detection system to assist drivers and improve road safety. The system integrates two main functions: an alert module that identifies and notifies the driver of detected signs (speed limits, prohibitions, stops, etc.), and a self-regulating speed module that allows the vehicle to automatically adjust its speed according to the recognized signs. A complementary mobile application allows the driver to change driving modes, monitor compliance with traffic signs, and access detailed statistics about their driving behavior.",
e5: "Processing of an MNIST image database.",
ed5: "This project involves applying image processing techniques to the MNIST database. The objective is to classify images based on color and texture descriptors and using the Sobel filter for edge detection, enabling the system to learn how to effectively recognize and categorize images according to their visual characteristics.",
e6: "Creation of a new lossless audio compression format.",
ed6: "This project focuses on the design and implementation of a new lossless audio format. The goal is to compress audio files, such as .wav files, while preserving the original quality and data entirely. The proposed format, named .IRM, is based on lossless compression algorithms such as Huffman, RLE, and LZW, in order to achieve an efficient file size reduction without any alteration of the audio signal.",
e7: "Development of a DESKTOP application for signal processing.",
ed7: "The goal of this project is to create an interface in MATLAB capable of calculating the Fourier transform for common signals such as cosine, sine, square, triangular, or sinc signals, as well as for signals extracted from audio files. This interface aims to simplify frequency analysis and provide a clear visualization of the spectral components of signals.",
e8: "Development of a website for hotel booking.",
ed8: "This project involves developing a website that allows users to book hotels in different Moroccan cities. The objective is to simplify the reservation process for travelers by providing an intuitive and accessible interface. Through this site, users can search, compare, and book hotels online quickly, conveniently, and securely, without having to travel.",
e9: "Java development of an application for sending SMS messages.",
ed9: "This project consists of developing a Java Swing interface that enables sending SMS messages without using a mobile phone. The goal is to design a simple and intuitive application that facilitates sending messages directly from a computer, using a gateway or a messaging API to ensure SMS delivery.",
    // =======================sertaficats==================
    t:"Download my certificate",

};
export const fr={
    titre: "Entrez dans mon univers",
home: "Accueil",
skills: "Compétences",
experiences: "Expériences",
certificates: "Certificats",
language: "Langue",
    // ====================home=============================
    b: "Bonjour,",
b1: " Je suis ",
b2: "Je suis un développeur ",
b3: "full-stack passionné.",
pre1: "Dédié à la création de solutions numériques intelligentes, efficaces et conviviales.",
pre2: "Qu’il s’agisse de développement web, mobile ou backend, j’aime transformer les idées en applications fonctionnelles. Bienvenue dans mon portfolio.",
pre3: "N’hésitez pas à explorer mes projets, mes compétences et mon expérience !",
cv: "Télécharger le CV",
Edu: "Formation",
In: "En cours",
Final: "Cinquième année du cycle ingénieur d’État.",
Fac: "Faculté des Sciences et Techniques de Fès.",
Major1: "Spécialité : Systèmes Intelligents, Communicants et Mobiles (SICOM).",
Bach: "Licence en Sciences et Techniques",
fac1: "Faculté des Sciences et Techniques de Mohammedia.",
Spe: "Spécialité : Informatique, Réseaux et Multimédia.",
bach1: "Diplôme d’Études Universitaires en Sciences et Techniques.",
spe: "Spécialité : Mathématiques, Informatique et Physique.",
Bac: "Baccalauréat en Sciences Physiques et Chimiques – Casablanca.",
ve1: "Version française",
ve2: "Version anglaise",
    // ======================skills========================
s1:"Langages de programmation",
s2:"Bibliothèques et frameworks",
s3:"Environnements de développement (IDE)",
s4:"Conception et planification des projets",
s5:"Bureautique",
s6:"Bases de données",
s7:"systèmes embarqués",
    // =======================experience==================
a:"Afficher les détails",
m:"Masquer les détails",
te1:"Stages",
en:"Environnement technique :",
e1:"Conception et développement d’une application web pour la numérisation des services de la bibliothèque de la FST.",
ed1:"Le but de ce projet est de concevoir et de développer une application web destinée à la gestion numérique des livres scientifiques de la bibliothèque de notre faculté.Cette plateforme offre également un espace collaboratif dédié aux étudiants et aux enseignants, leur permettant d’échanger des documents tels que des cours, des TD et des TP.En outre, un forum de discussion a été intégré afin de favoriser une meilleure communication et un partage de connaissances au sein de la communauté universitaire.",
e2:"Conception et développement d’une application mobile permettant aux épiciers depasser leurs commandes en ligne.",
ed2:"Ce projet consiste à concevoir et développer une application mobile destinée aux épiciers, leur permettant de passer leurs commandes en ligne auprès de leur fournisseur principal, Centrale Danone. L’application propose plusieurs fonctionnalités essentielles telles que le suivi en temps réel des commandes, la gestion des clients (épiciers) à travers un espace personnalisé, ainsi qu’un module de reporting pour l’analyse des ventes et des performances commerciales. L’objectif principal de cette solution est de digitaliser le processus de commande entre Centrale Danone et ses revendeurs, de faciliter la communication et la logistique, et d’améliorer la gestion et le suivi des activités commerciales à travers une interface intuitive, moderne et accessible à tous.",
e3:"Conception et Développement d’une application mobile pour la gestion d’un cabinet dentaire.",
ed3:"Ce projet porte sur la conception et le développement d’une application mobile dédiée à la gestion complète d’un cabinet dentaire. L’objectif est de proposer une solution numérique intégrée permettant de centraliser et de simplifier les principales activités du cabinet, notamment la gestion des rendez-vous avec un calendrier interactif, la gestion des dossiers médicaux des patients incluant les antécédents, les diagnostics et les traitements effectués, ainsi que la gestion des médicaments et des prescriptions. L’application intègre également un service d’aide et de communication pour les patients, leur offrant la possibilité de poser des questions, de recevoir des rappels automatiques de rendez-vous et de suivre leurs traitements. Cette solution vise à améliorer l’organisation interne du cabinet, à optimiser le suivi médical et à renforcer la relation entre le praticien et ses patients grâce à une interface moderne, ergonomique et sécurisée.",
te2:"Projets académiques",
e4:"Développement d’un système intelligent pour la détection des panneaux de signalisation routière.",
ed4:"Ce projet porte sur la conception et la réalisation d’un système intelligent de détection des panneaux de signalisation en temps réel, destiné à assister les conducteurs et à améliorer la sécurité routière. Le système intègre deux principales fonctionnalités : une partie d’alerte, qui identifie et signale au conducteur les panneaux détectés (limitation de vitesse, interdiction, arrêt, etc.), et une partie d’autorégulation de la vitesse, permettant au véhicule d’ajuster automatiquement sa vitesse en fonction des panneaux reconnus. Une application mobile complémentaire permet au conducteur de changer les modes de conduite, de suivre son respect des signalisations et de consulter des statistiques détaillées sur son comportement routier.",
e5:"Traitement d'une base de données d'images MNIST. ",
ed5:"Ce projet consiste à appliquer des techniques de traitement d’image sur la base de données MNIST. L’objectif est de classifier les images à partir de descripteurs de couleur, de texture et à l’aide du filtre de Sobel pour la détection des contours, afin de permettre au système d’apprendre à reconnaître et à classer efficacement les images selon leurs caractéristiques visuelles.",
e6:"Création d'un nouveau format de compression audio sans perte.",
ed6:"Ce projet porte sur la conception et la réalisation d’un nouveau format audio sans perte. L’objectif est de compresser des fichiers audio, tels que ceux au format .wav, tout en préservant intégralement la qualité et les données d’origine. Le format proposé, nommé .IRM, repose sur l’utilisation d’algorithmes de compression sans perte tels que Huffman, RLE et LZW, afin d’obtenir une réduction efficace de la taille des fichiers sans altération du signal audio.",
e7:"Réalisation d’une application DESKTOP pour le traitement du signal.",
ed7:"Le but de ce projet est de réaliser une interface sous MATLAB permettant de calculer la transformée de Fourier pour des signaux usuels tels que le cosinus, le sinus, le signal carré, le signal triangulaire ou le sinus cardinal, ainsi que pour des signaux extraits de fichiers audio. Cette interface vise à faciliter l’analyse fréquentielle des signaux et à offrir une visualisation claire de leurs composantes spectrales.",
e8:"Développement d’un site web pour la réservation d’hôtels.",
ed8:"Ce projet consiste à développer un site web permettant de réserver des hôtels dans différentes villes marocaines. L’objectif est de simplifier le processus de réservation pour les voyageurs en leur offrant une interface intuitive et accessible. Grâce à ce site, les utilisateurs peuvent rechercher, comparer et réserver des hôtels en ligne de manière rapide, pratique et sécurisée, sans avoir à se déplacer.",
e9:"Développement par java d’une application pour l’envoi des SMS.",
ed9:"Ce projet consiste en la réalisation d’une interface développée avec Java Swing permettant l’envoi de SMS sans recourir à un téléphone. L’objectif est de concevoir une application simple et intuitive qui facilite l’envoi de messages directement depuis un ordinateur, en utilisant une passerelle ou une API de messagerie pour assurer la transmission des SMS.",
// =======================certaficats==================
    t:"Télécharger mon certificat",
}